map_updater:
  ros__parameters:
    model: Pinhole
    width: 1280
    height: 720
    scale: 1.0
    fx: 631.1903076171875
    fy: 630.41162109375
    cx: 628.8812255859375
    cy: 371.5096435546875
    d0: -0.055450838059186935
    d1: 0.06841126084327698
    d2: -3.5516146454028785e-05
    d3: -0.00010084670066135004